version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    open-pull-requests-limit: 10
    assignees:
      - "ezedike-evan"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    open-pull-requests-limit: 5
    assignees:
      - "ezedike-evan"
    labels:
      - "ci"
    commit-message:
      prefix: "chore"
