#!/usr/bin/env node
// Writes packages/core/tests/fixtures/COVERAGE.md: which XDR union arms the REAL recorded
// corpus exercises, and which it does not. Gaps are listed, not hidden: an arm with no real
// fixture is an arm whose decoder has not been checked against the official tool.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const fixtures = resolve(here, '../../core/tests/fixtures');
const data = JSON.parse(readFileSync(resolve(fixtures, 'soroban-xdr.json'), 'utf8'));

const keyOf = (o) => (typeof o === 'string' ? o : Object.keys(o)[0]);
const seen = { scval: new Map(), ledgerKey: new Map(), eventType: new Map(), credentials: new Map(), spec: new Map(), entry: new Map(), txResult: new Map() };
const bump = (m, k) => m.set(k, (m.get(k) ?? 0) + 1);

function walkScVal(o) {
  if (o === null || o === undefined) return;
  if (typeof o === 'string') { if (o === 'void' || o.startsWith('ledger_key')) bump(seen.scval, o); return; }
  if (Array.isArray(o)) { o.forEach(walkScVal); return; }
  const k = Object.keys(o)[0];
  if (['bool','u32','i32','u64','i64','timepoint','duration','u128','i128','u256','i256','bytes','string','symbol','vec','map','address','error','contract_instance'].includes(k)) bump(seen.scval, k);
  if (k === 'vec' && o.vec) o.vec.forEach(walkScVal);
  if (k === 'map' && o.map) o.map.forEach((e) => { walkScVal(e.key); walkScVal(e.val); });
  if (k === 'contract_instance' && o.contract_instance.storage) o.contract_instance.storage.forEach((e) => { walkScVal(e.key); walkScVal(e.val); });
}

for (const item of data.items) {
  const o = item.oracle;
  if (item.type === 'ScVal') walkScVal(o);
  if (item.type === 'DiagnosticEvent') {
    bump(seen.eventType, o.event.type_);
    o.event.body.v0.topics.forEach(walkScVal);
    walkScVal(o.event.body.v0.data);
  }
  if (item.type === 'SorobanTransactionData') {
    for (const k of [...o.resources.footprint.read_only, ...o.resources.footprint.read_write]) {
      bump(seen.ledgerKey, keyOf(k));
      if (k.contract_data) walkScVal(k.contract_data.key);
    }
  }
  if (item.type === 'LedgerKey') {
    bump(seen.ledgerKey, keyOf(o));
    if (o.contract_data) walkScVal(o.contract_data.key);
  }
  if (item.type === 'SorobanAuthorizationEntry') bump(seen.credentials, typeof o.credentials === 'string' ? o.credentials : keyOf(o.credentials));
  if (item.type === 'LedgerEntryData') {
    bump(seen.entry, keyOf(o));
    if (o.contract_data) { walkScVal(o.contract_data.key); walkScVal(o.contract_data.val); }
  }
  if (item.type === 'TransactionResult') bump(seen.txResult, keyOf(o.result));
}
for (const c of data.contracts ?? []) {
  for (const e of c.oracleSpec ?? []) bump(seen.spec, keyOf(e));
  // Each captured contract has a real contract-code entry and key. spec.oracle.test.ts checks the
  // key against the one the stellar CLI builds, and the entry's code against the WASM bytes.
  bump(seen.entry, 'contract_code');
  bump(seen.ledgerKey, 'contract_code');
}

const ALL = {
  scval: ['bool','void','error','u32','i32','u64','i64','timepoint','duration','u128','i128','u256','i256','bytes','string','symbol','vec','map','address','contract_instance','ledger_key_contract_instance','ledger_key_nonce'],
  ledgerKey: ['account','trustline','offer','data','claimable_balance','liquidity_pool','contract_data','contract_code','config_setting','ttl'],
  eventType: ['system','contract','diagnostic'],
  credentials: ['source_account','address'],
  spec: ['function_v0','udt_struct_v0','udt_union_v0','udt_enum_v0','udt_error_enum_v0','event_v0'],
  entry: ['contract_data','contract_code','ttl'],
};
const TITLES = { scval: 'ScVal', ledgerKey: 'LedgerKey (in footprints and keys)', eventType: 'ContractEventType', credentials: 'SorobanCredentials', spec: 'ScSpecEntry', entry: 'LedgerEntryData' };

const lines = [
  '# Fixture coverage',
  '',
  `Generated by \`packages/test-utils/scripts/coverage-matrix.mjs\` from \`soroban-xdr.json\` (recorded ${data.provenance.recordedAt}, ledger ${data.provenance.latestLedger}, ${data.provenance.stellarCli}).`,
  '',
  'Each decoder is checked against the official `stellar xdr decode` output for **real** XDR captured from the live network. This file lists which union arms that corpus actually contains. An arm marked **not covered** has a decoder that has not been checked against the official tool, because the live network did not produce an example on demand. Close the gap by recording one, never by writing one by hand.',
  '',
];
let gaps = 0;
for (const [key, arms] of Object.entries(ALL)) {
  lines.push(`## ${TITLES[key]}`, '', '| Arm | Real examples |', '|---|---:|');
  for (const arm of arms) {
    const n = seen[key].get(arm) ?? 0;
    if (n === 0) gaps += 1;
    lines.push(`| \`${arm}\` | ${n === 0 ? '**not covered**' : n} |`);
  }
  lines.push('');
}
lines.push('## TransactionResult codes seen', '', [...seen.txResult].map(([k, n]) => `\`${k}\` (${n})`).join(', ') || 'none', '');
writeFileSync(resolve(fixtures, 'COVERAGE.md'), lines.join('\n'));
console.log(`wrote COVERAGE.md (${gaps} arm(s) not covered)`);
