// Generated by scripts/gen-api-reference.mjs. Do not edit.
import type { DocItem } from './docroutes'

export const referenceItems: DocItem[] = [
  {
    "title": "Overview",
    "href": "/docs/reference"
  },
  {
    "title": "AllProvidersFailedError",
    "href": "/docs/reference/allprovidersfailederror"
  },
  {
    "title": "ContractNotFoundError",
    "href": "/docs/reference/contractnotfounderror"
  },
  {
    "title": "ContractSpec",
    "href": "/docs/reference/contractspec"
  },
  {
    "title": "NoEligibleProviderError",
    "href": "/docs/reference/noeligibleprovidererror"
  },
  {
    "title": "ProviderRegistry",
    "href": "/docs/reference/providerregistry"
  },
  {
    "title": "RpcClient",
    "href": "/docs/reference/rpcclient"
  },
  {
    "title": "RpcError",
    "href": "/docs/reference/rpcerror"
  },
  {
    "title": "RpcHttpError",
    "href": "/docs/reference/rpchttperror"
  },
  {
    "title": "RpcNetworkError",
    "href": "/docs/reference/rpcnetworkerror"
  },
  {
    "title": "RpcProtocolError",
    "href": "/docs/reference/rpcprotocolerror"
  },
  {
    "title": "RpcResponseError",
    "href": "/docs/reference/rpcresponseerror"
  },
  {
    "title": "RpcTimeoutError",
    "href": "/docs/reference/rpctimeouterror"
  },
  {
    "title": "SimulationError",
    "href": "/docs/reference/simulationerror"
  },
  {
    "title": "SoroscopeRouter",
    "href": "/docs/reference/soroscoperouter"
  },
  {
    "title": "TransactionSimulator",
    "href": "/docs/reference/transactionsimulator"
  },
  {
    "title": "XdrDecodeError",
    "href": "/docs/reference/xdrdecodeerror"
  },
  {
    "title": "XdrUnsupportedError",
    "href": "/docs/reference/xdrunsupportederror"
  },
  {
    "title": "Attempt",
    "href": "/docs/reference/attempt"
  },
  {
    "title": "AuthEntry",
    "href": "/docs/reference/authentry"
  },
  {
    "title": "AuthorizedInvocation",
    "href": "/docs/reference/authorizedinvocation"
  },
  {
    "title": "BurstResult",
    "href": "/docs/reference/burstresult"
  },
  {
    "title": "CatalogEntry",
    "href": "/docs/reference/catalogentry"
  },
  {
    "title": "ContractCode",
    "href": "/docs/reference/contractcode"
  },
  {
    "title": "ContractCodeCostInputs",
    "href": "/docs/reference/contractcodecostinputs"
  },
  {
    "title": "ContractErrorInfo",
    "href": "/docs/reference/contracterrorinfo"
  },
  {
    "title": "ContractEvent",
    "href": "/docs/reference/contractevent"
  },
  {
    "title": "ContractFailure",
    "href": "/docs/reference/contractfailure"
  },
  {
    "title": "DecodedOperationResult",
    "href": "/docs/reference/decodedoperationresult"
  },
  {
    "title": "DecodedScError",
    "href": "/docs/reference/decodedscerror"
  },
  {
    "title": "DecodedTransactionResult",
    "href": "/docs/reference/decodedtransactionresult"
  },
  {
    "title": "DetailedResult",
    "href": "/docs/reference/detailedresult"
  },
  {
    "title": "DiagnosticEvent",
    "href": "/docs/reference/diagnosticevent"
  },
  {
    "title": "Exclusion",
    "href": "/docs/reference/exclusion"
  },
  {
    "title": "LatencyStat",
    "href": "/docs/reference/latencystat"
  },
  {
    "title": "LatencySummary",
    "href": "/docs/reference/latencysummary"
  },
  {
    "title": "LedgerFootprint",
    "href": "/docs/reference/ledgerfootprint"
  },
  {
    "title": "LedgerObservation",
    "href": "/docs/reference/ledgerobservation"
  },
  {
    "title": "MethodProfile",
    "href": "/docs/reference/methodprofile"
  },
  {
    "title": "ParsedWasm",
    "href": "/docs/reference/parsedwasm"
  },
  {
    "title": "PerProviderResult",
    "href": "/docs/reference/perproviderresult"
  },
  {
    "title": "ProbeOptions",
    "href": "/docs/reference/probeoptions"
  },
  {
    "title": "ProbeReport",
    "href": "/docs/reference/probereport"
  },
  {
    "title": "ProviderInput",
    "href": "/docs/reference/providerinput"
  },
  {
    "title": "ProviderProbe",
    "href": "/docs/reference/providerprobe"
  },
  {
    "title": "ProviderRecord",
    "href": "/docs/reference/providerrecord"
  },
  {
    "title": "RawSimulateResponse",
    "href": "/docs/reference/rawsimulateresponse"
  },
  {
    "title": "RawStateChange",
    "href": "/docs/reference/rawstatechange"
  },
  {
    "title": "RegistryConfig",
    "href": "/docs/reference/registryconfig"
  },
  {
    "title": "RegistrySnapshot",
    "href": "/docs/reference/registrysnapshot"
  },
  {
    "title": "RetentionRange",
    "href": "/docs/reference/retentionrange"
  },
  {
    "title": "RouteExplanation",
    "href": "/docs/reference/routeexplanation"
  },
  {
    "title": "RouterCallOptions",
    "href": "/docs/reference/routercalloptions"
  },
  {
    "title": "RouterConfig",
    "href": "/docs/reference/routerconfig"
  },
  {
    "title": "RoutingRequirements",
    "href": "/docs/reference/routingrequirements"
  },
  {
    "title": "RpcCaller",
    "href": "/docs/reference/rpccaller"
  },
  {
    "title": "RpcCallOptions",
    "href": "/docs/reference/rpccalloptions"
  },
  {
    "title": "RpcClientConfig",
    "href": "/docs/reference/rpcclientconfig"
  },
  {
    "title": "RpcRawResult",
    "href": "/docs/reference/rpcrawresult"
  },
  {
    "title": "ScAddress",
    "href": "/docs/reference/scaddress"
  },
  {
    "title": "ScMapEntry",
    "href": "/docs/reference/scmapentry"
  },
  {
    "title": "SimulateOptions",
    "href": "/docs/reference/simulateoptions"
  },
  {
    "title": "SimulateTransactionParams",
    "href": "/docs/reference/simulatetransactionparams"
  },
  {
    "title": "SimulationReport",
    "href": "/docs/reference/simulationreport"
  },
  {
    "title": "SorobanResources",
    "href": "/docs/reference/sorobanresources"
  },
  {
    "title": "SorobanTransactionData",
    "href": "/docs/reference/sorobantransactiondata"
  },
  {
    "title": "SpecEnum",
    "href": "/docs/reference/specenum"
  },
  {
    "title": "SpecEnumCase",
    "href": "/docs/reference/specenumcase"
  },
  {
    "title": "SpecErrorEnum",
    "href": "/docs/reference/specerrorenum"
  },
  {
    "title": "SpecEvent",
    "href": "/docs/reference/specevent"
  },
  {
    "title": "SpecEventParam",
    "href": "/docs/reference/speceventparam"
  },
  {
    "title": "SpecField",
    "href": "/docs/reference/specfield"
  },
  {
    "title": "SpecFunction",
    "href": "/docs/reference/specfunction"
  },
  {
    "title": "SpecStruct",
    "href": "/docs/reference/specstruct"
  },
  {
    "title": "SpecUnion",
    "href": "/docs/reference/specunion"
  },
  {
    "title": "SpecUnionCase",
    "href": "/docs/reference/specunioncase"
  },
  {
    "title": "StateChange",
    "href": "/docs/reference/statechange"
  },
  {
    "title": "TableRow",
    "href": "/docs/reference/tablerow"
  },
  {
    "title": "TransactionErrorInput",
    "href": "/docs/reference/transactionerrorinput"
  },
  {
    "title": "authorizer",
    "href": "/docs/reference/authorizer"
  },
  {
    "title": "base64ToBytes",
    "href": "/docs/reference/base64tobytes"
  },
  {
    "title": "bytesToBase64",
    "href": "/docs/reference/bytestobase64"
  },
  {
    "title": "canonicalLedgerKey",
    "href": "/docs/reference/canonicalledgerkey"
  },
  {
    "title": "classifyFailure",
    "href": "/docs/reference/classifyfailure"
  },
  {
    "title": "contractCodeKey",
    "href": "/docs/reference/contractcodekey"
  },
  {
    "title": "contractInstanceKey",
    "href": "/docs/reference/contractinstancekey"
  },
  {
    "title": "decodeAccountId",
    "href": "/docs/reference/decodeaccountid"
  },
  {
    "title": "decodeAuthEntry",
    "href": "/docs/reference/decodeauthentry"
  },
  {
    "title": "decodeContractEvent",
    "href": "/docs/reference/decodecontractevent"
  },
  {
    "title": "decodeContractId",
    "href": "/docs/reference/decodecontractid"
  },
  {
    "title": "decodeDiagnosticEvent",
    "href": "/docs/reference/decodediagnosticevent"
  },
  {
    "title": "decodeLedgerEntryData",
    "href": "/docs/reference/decodeledgerentrydata"
  },
  {
    "title": "decodeLedgerKey",
    "href": "/docs/reference/decodeledgerkey"
  },
  {
    "title": "decodeScError",
    "href": "/docs/reference/decodescerror"
  },
  {
    "title": "decodeScVal",
    "href": "/docs/reference/decodescval"
  },
  {
    "title": "decodeSimulationResponse",
    "href": "/docs/reference/decodesimulationresponse"
  },
  {
    "title": "decodeSorobanTransactionData",
    "href": "/docs/reference/decodesorobantransactiondata"
  },
  {
    "title": "decodeSpecEntries",
    "href": "/docs/reference/decodespecentries"
  },
  {
    "title": "decodeStrkey",
    "href": "/docs/reference/decodestrkey"
  },
  {
    "title": "decodeTransactionResult",
    "href": "/docs/reference/decodetransactionresult"
  },
  {
    "title": "describeInvocationTree",
    "href": "/docs/reference/describeinvocationtree"
  },
  {
    "title": "describeSimulation",
    "href": "/docs/reference/describesimulation"
  },
  {
    "title": "encodeAccountId",
    "href": "/docs/reference/encodeaccountid"
  },
  {
    "title": "encodeContractId",
    "href": "/docs/reference/encodecontractid"
  },
  {
    "title": "eventName",
    "href": "/docs/reference/eventname"
  },
  {
    "title": "explainTransactionError",
    "href": "/docs/reference/explaintransactionerror"
  },
  {
    "title": "fetchContractCode",
    "href": "/docs/reference/fetchcontractcode"
  },
  {
    "title": "fetchContractSpec",
    "href": "/docs/reference/fetchcontractspec"
  },
  {
    "title": "fetchWasm",
    "href": "/docs/reference/fetchwasm"
  },
  {
    "title": "findFailure",
    "href": "/docs/reference/findfailure"
  },
  {
    "title": "formatScVal",
    "href": "/docs/reference/formatscval"
  },
  {
    "title": "formatSpecType",
    "href": "/docs/reference/formatspectype"
  },
  {
    "title": "formatTransactionResult",
    "href": "/docs/reference/formattransactionresult"
  },
  {
    "title": "fromHex",
    "href": "/docs/reference/fromhex"
  },
  {
    "title": "ledgerObservationOf",
    "href": "/docs/reference/ledgerobservationof"
  },
  {
    "title": "parseErrorText",
    "href": "/docs/reference/parseerrortext"
  },
  {
    "title": "parseRetentionRange",
    "href": "/docs/reference/parseretentionrange"
  },
  {
    "title": "parseRetryAfter",
    "href": "/docs/reference/parseretryafter"
  },
  {
    "title": "parseWasm",
    "href": "/docs/reference/parsewasm"
  },
  {
    "title": "probeProviders",
    "href": "/docs/reference/probeproviders"
  },
  {
    "title": "profileOf",
    "href": "/docs/reference/profileof"
  },
  {
    "title": "providerIdOf",
    "href": "/docs/reference/provideridof"
  },
  {
    "title": "publicProviderUrls",
    "href": "/docs/reference/publicproviderurls"
  },
  {
    "title": "readLedgerEntryData",
    "href": "/docs/reference/readledgerentrydata"
  },
  {
    "title": "readLedgerKey",
    "href": "/docs/reference/readledgerkey"
  },
  {
    "title": "readScAddress",
    "href": "/docs/reference/readscaddress"
  },
  {
    "title": "readScError",
    "href": "/docs/reference/readscerror"
  },
  {
    "title": "readScVal",
    "href": "/docs/reference/readscval"
  },
  {
    "title": "resolveContractError",
    "href": "/docs/reference/resolvecontracterror"
  },
  {
    "title": "scValToJs",
    "href": "/docs/reference/scvaltojs"
  },
  {
    "title": "startLedgerOf",
    "href": "/docs/reference/startledgerof"
  },
  {
    "title": "toHex",
    "href": "/docs/reference/tohex"
  },
  {
    "title": "toJson",
    "href": "/docs/reference/tojson"
  },
  {
    "title": "toJsonSafe",
    "href": "/docs/reference/tojsonsafe"
  },
  {
    "title": "toPrometheus",
    "href": "/docs/reference/toprometheus"
  },
  {
    "title": "toTable",
    "href": "/docs/reference/totable"
  },
  {
    "title": "toTableRows",
    "href": "/docs/reference/totablerows"
  },
  {
    "title": "Asset",
    "href": "/docs/reference/asset"
  },
  {
    "title": "AuthCredentials",
    "href": "/docs/reference/authcredentials"
  },
  {
    "title": "AuthorizedFunction",
    "href": "/docs/reference/authorizedfunction"
  },
  {
    "title": "ContractDataDurability",
    "href": "/docs/reference/contractdatadurability"
  },
  {
    "title": "ContractEventType",
    "href": "/docs/reference/contracteventtype"
  },
  {
    "title": "ContractExecutable",
    "href": "/docs/reference/contractexecutable"
  },
  {
    "title": "ContractIdPreimage",
    "href": "/docs/reference/contractidpreimage"
  },
  {
    "title": "ContractMeta",
    "href": "/docs/reference/contractmeta"
  },
  {
    "title": "ContractSource",
    "href": "/docs/reference/contractsource"
  },
  {
    "title": "FailureClass",
    "href": "/docs/reference/failureclass"
  },
  {
    "title": "HistoryKind",
    "href": "/docs/reference/historykind"
  },
  {
    "title": "LedgerEntryData",
    "href": "/docs/reference/ledgerentrydata"
  },
  {
    "title": "LedgerKey",
    "href": "/docs/reference/ledgerkey"
  },
  {
    "title": "NetworkId",
    "href": "/docs/reference/networkid"
  },
  {
    "title": "ProviderStatus",
    "href": "/docs/reference/providerstatus"
  },
  {
    "title": "RpcMethod",
    "href": "/docs/reference/rpcmethod"
  },
  {
    "title": "ScVal",
    "href": "/docs/reference/scval"
  },
  {
    "title": "SpecEntry",
    "href": "/docs/reference/specentry"
  },
  {
    "title": "SpecType",
    "href": "/docs/reference/spectype"
  },
  {
    "title": "XdrErrorCategory",
    "href": "/docs/reference/xdrerrorcategory"
  },
  {
    "title": "HARD_FAILURES",
    "href": "/docs/reference/hard_failures"
  },
  {
    "title": "LEDGER_CLOSE_MS",
    "href": "/docs/reference/ledger_close_ms"
  },
  {
    "title": "NETWORK_PASSPHRASES",
    "href": "/docs/reference/network_passphrases"
  },
  {
    "title": "PUBLIC_PROVIDERS",
    "href": "/docs/reference/public_providers"
  }
]
